version: '2.0'

services:
    nginx-proxy:
        image: jwilder/nginx-proxy:0.4.0
        ports:
            - "8081:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
   default:
      ipam:
         config:
            - subnet: 172.28.0.0/16
